<def f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='605' ll='612' type='boost::contract::from_failure_handler boost::contract::get_postcondition_failure()'/>
<doc f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='593'>/**
Return failure handler currently set for postconditions.

This is often called only internally by this library.

@b Throws: This is declared @c noexcept (or @c throw() before C++11).

@return A copy of the failure handler currently set.

@see    @RefSect{advanced.throw_on_failures__and__noexcept__, Throw on Failure},
        @RefSect{tutorial.postconditions, Postconditions}
*/</doc>
