<def f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='123' ll='125' type='void boost::fibers::promise_already_satisfied::promise_already_satisfied()'/>
