<dec f='boost-1.85.0/libs/log/include/boost/log/exceptions.hpp' l='330' type='void boost::log::logic_error::logic_error(const std::string &amp; descr)'/>
<doc f='boost-1.85.0/libs/log/include/boost/log/exceptions.hpp' l='327'>/*!
     * Initializing constructor. Creates an exception with the specified error message.
     */</doc>
<def f='boost-1.85.0/libs/log/src/exceptions.cpp' l='461' ll='464' type='void boost::log::logic_error::logic_error(const std::string &amp; descr)'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='472' u='c' c='_ZN5boost3log12v2s_mt_posix11logic_error6throw_EPKcmS4_'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='480' u='c' c='_ZN5boost3log12v2s_mt_posix11logic_error6throw_EPKcmRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='487' u='c' c='_ZN5boost3log12v2s_mt_posix13odr_violationC1Ev'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='492' u='c' c='_ZN5boost3log12v2s_mt_posix13odr_violationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='525' u='c' c='_ZN5boost3log12v2s_mt_posix15unexpected_callC1Ev'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='530' u='c' c='_ZN5boost3log12v2s_mt_posix15unexpected_callC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='563' u='c' c='_ZN5boost3log12v2s_mt_posix11setup_errorC1Ev'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='568' u='c' c='_ZN5boost3log12v2s_mt_posix11setup_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='601' u='c' c='_ZN5boost3log12v2s_mt_posix16limitation_errorC1Ev'/>
<use f='boost-1.85.0/libs/log/src/exceptions.cpp' l='606' u='c' c='_ZN5boost3log12v2s_mt_posix16limitation_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
