<def f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='260' ll='266' type='void boost::exception::exception()'/>
<use f='boost-1.85.0/libs/xpressive/include/boost/xpressive/regex_error.hpp' l='58' u='c' c='_ZN5boost9xpressive11regex_errorC1ENS0_15regex_constants10error_typeEPKc'/>
