<def f='boost-1.85.0/libs/interprocess/include/boost/interprocess/exceptions.hpp' l='71' type='boost::interprocess::error_code_t boost::interprocess::interprocess_exception::get_error_code() const'/>
<use f='boost-1.85.0/libs/log/src/posix/ipc_reliable_message_queue.cpp' l='298' u='c' c='_ZN5boost3log12v2s_mt_posix3ipc22reliable_message_queue14implementationC1ENS1_9open_mode18open_or_create_tagERKNS2_11object_nameEjjNS3_15overflow_poli5819404'/>
<use f='boost-1.85.0/libs/log/src/posix/ipc_reliable_message_queue.cpp' l='319' u='c' c='_ZN5boost3log12v2s_mt_posix3ipc22reliable_message_queue14implementationC1ENS1_9open_mode18open_or_create_tagERKNS2_11object_nameEjjNS3_15overflow_poli5819404'/>
<doc f='boost-1.85.0/libs/interprocess/include/boost/interprocess/exceptions.hpp' l='70'>// Note: a value of other_error implies a library (rather than system) error</doc>
