<inh f='boost-1.85.0/libs/wave/include/boost/wave/cpp_exceptions.hpp' l='168' c='_ZNK5boost4wave20preprocess_exception4whatEv'/>
<def f='boost-1.85.0/libs/wave/include/boost/wave/cpp_exceptions.hpp' l='402' ll='405' type='const char * boost::wave::macro_handling_exception::what() const'/>
