<def f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='236' ll='248'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='261'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='311' c='_ZN5boost8contract10exception_20pre_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='313' c='_ZN5boost8contract10exception_18pre_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='330' c='_ZN5boost8contract10exception_21post_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='332' c='_ZN5boost8contract10exception_19post_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='350' c='_ZN5boost8contract10exception_23except_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='352' c='_ZN5boost8contract10exception_21except_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='369' c='_ZN5boost8contract10exception_20old_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='371' c='_ZN5boost8contract10exception_18old_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='390' c='_ZN5boost8contract10exception_26entry_inv_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='392' c='_ZN5boost8contract10exception_24entry_inv_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='411' c='_ZN5boost8contract10exception_25exit_inv_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='413' c='_ZN5boost8contract10exception_23exit_inv_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='560' c='_ZN5boost8contract20precondition_failureENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='630' c='_ZN5boost8contract21postcondition_failureENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='703' c='_ZN5boost8contract14except_failureENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='772' c='_ZN5boost8contract11old_failureENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='848' c='_ZN5boost8contract23entry_invariant_failureENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='924' c='_ZN5boost8contract22exit_invariant_failureENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='127' c='_ZN5boost8contract10exception_20default_from_handlerENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='189'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='219' c='_ZN5boost8contract10exception_20pre_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='224' c='_ZN5boost8contract10exception_18pre_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='239'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='269' c='_ZN5boost8contract10exception_21post_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='274' c='_ZN5boost8contract10exception_19post_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='289'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='320' c='_ZN5boost8contract10exception_23except_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='325' c='_ZN5boost8contract10exception_21except_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='340'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='370' c='_ZN5boost8contract10exception_20old_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='375' c='_ZN5boost8contract10exception_18old_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='390'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='422' c='_ZN5boost8contract10exception_26entry_inv_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='427' c='_ZN5boost8contract10exception_24entry_inv_failure_lockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='442'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='474' c='_ZN5boost8contract10exception_25exit_inv_failure_unlockedENS0_4fromE'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='479' c='_ZN5boost8contract10exception_23exit_inv_failure_lockedENS0_4fromE'/>
<doc f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='225'>/**
Indicate the kind of operation where the contract assertion failed.

This is passed as a parameter to the assertion failure handler functions.
For example, it might be necessary to know in which operation an assertion
failed to make sure exceptions are never thrown from destructors, not even
when contract failure handlers are programmed by users to throw exceptions
instead of terminating the program.

@see @RefSect{advanced.throw_on_failures__and__noexcept__, Throw on Failure}
*/</doc>
