<dec f='qtbase-6.5.0/src/network/socket/qabstractsocket.h' l='77' type='15'/>
<doc f='qtbase-6.5.0/src/network/socket/qabstractsocket.h' l='77'>/* 15 */</doc>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='1039' c='_ZN29QHttpNetworkConnectionChannel8_q_errorEN15QAbstractSocket11SocketErrorE'/>
<use f='qtbase-6.5.0/src/network/socket/qabstractsocket.cpp' l='479' c='_ZL12isProxyErrorN15QAbstractSocket11SocketErrorE'/>
<use f='qtbase-6.5.0/src/network/socket/qabstractsocket.cpp' l='2923' c='_Zls6QDebugN15QAbstractSocket11SocketErrorE'/>
<doc f='qtbase-6.5.0/src/network/socket/qabstractsocket.cpp' l='279'>\value ProxyConnectionClosedError The connection to the proxy server was closed
           unexpectedly (before the connection to the final peer was established)
    </doc>
<use f='qtbase-6.5.0/src/network/socket/qhttpsocketengine.cpp' l='700' u='r' c='_ZN17QHttpSocketEngine15slotSocketErrorEN15QAbstractSocket11SocketErrorE'/>
<use f='qtbase-6.5.0/src/network/socket/qsocks5socketengine.cpp' l='567' u='r' c='_ZN26QSocks5SocketEnginePrivate13setErrorStateENS_11Socks5StateERK7QString'/>
